apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    project: roboshop
    tier: backend
    component: app1
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: app1
  replicas: 1
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: app1   
    spec:
      containers:
        - name: app1
          image: saithota9/app1:1.0.0
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    project: roboshop
    tier: backend
    component: app1 
spec:
  selector:
    project: roboshop
    tier: backend
    component: app1 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-ingress
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb  # Specifies the Ingress Controller to use
  rules:
  - host: app1.devopswiththota.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1
            port:
              number: 80
